name: Build Push Docker Image To Amazon ECR

on:
  push:
    paths:
      - "services/users/**"
  pull_request:

env:
  ECR_REPO_NAME: whatdoing
  IMAGE_TAG_LATEST: latest
  IMAGE_TAG_SHA: ${{ github.sha }}
  AWS_REGION: us-east-2

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image to Amazon ECR
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          # push: false
          context: ./services/users/
          file: ./services/users/Dockerfile
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG_LATEST }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG_SHA }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
